# Generated by Django 5.1.7 on 2025-04-12 19:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[core.models.validar_nome_sem_numeros]),
        ),
    ]
